In [1]:
from google.colab import drive
drive.mount('/content/drive')
%cd "/content/drive/MyDrive/GoogleColab/SA/ShortAnswer/"

Mounted at /content/drive
/content/drive/MyDrive/GoogleColab/SA/ShortAnswer


In [ ]:
from sklearn.model_selection import KFold
import json
import numpy as np
with open('./Y14/Y14_2-2_2_3.json') as f:
  train_dataf = json.load(f)
kf = KFold(n_splits=5)
for ind, train_test_ind in enumerate(kf.split(train_dataf)):
  with open('./Y14/2-2_2_3/data/fold{}/train_data.json'.format(ind), 'w') as f:
    json.dump(list(np.array(train_dataf)[train_test_ind[0]]), f, ensure_ascii=False)
  with open('./Y14/2-2_2_3/data/fold{}/test_data.json'.format(ind), 'w') as f:
    json.dump(list(np.array(train_dataf)[train_test_ind[1]]), f, ensure_ascii=False)

In [ ]:
from sklearn.model_selection import KFold
import json
import numpy as np
with open('./Y14/Y14_2-2_2_3.json') as f:
  train_dataf = json.load(f)
kf = KFold(n_splits=5)
for ind, train_test_ind in enumerate(kf.split(train_dataf)):

In [ ]:
from sklearn.model_selection import KFold
import json
import numpy as np
with open('./Y15/Y15_2-3_1_5.json') as f:
  train_dataf = json.load(f)

In [ ]:
kf = KFold(n_splits=5, shuffle=True)
x = np.arange(len(train_dataf))
dataf_splited = []
for _fold, (train_index, test_index) in enumerate(kf.split(x)):
  print(test_index[:20])
  dataf_splited.append([train_dataf[i] for i in test_index])

[ 11  12  16  19  20  29  36  38  47  50  57  62  64  66  72  81  84 102
 110 112]
[ 1  2 15 18 21 22 32 40 48 53 54 59 74 75 79 80 83 86 91 93]
[  5   8  10  13  14  25  26  30  43  44  49  51  63  65  68  87  89  95
  99 103]
[ 0  3  4  7 24 27 31 35 39 45 46 55 61 67 69 71 76 78 88 90]
[ 6  9 17 23 28 33 34 37 41 42 52 56 58 60 70 73 77 82 85 94]


In [8]:
from sklearn.model_selection import KFold
import json
import numpy as np

with open('./Y15/Y15_2-3_2_2.json') as f:
  train_dataf = json.load(f)

kf = KFold(n_splits=5, shuffle=True)
x = np.arange(len(train_dataf))
dataf_splited = []
for _fold, (train_index, test_index) in enumerate(kf.split(x)):
  print(test_index)
  dataf_splited.append([train_dataf[i] for i in test_index])

[  11   13   18   34   38   45   48   57   58   59   64   68   73   86
   91   99  101  108  111  117  118  120  125  134  137  141  144  155
  157  162  164  168  180  185  200  202  203  206  212  217  230  231
  234  249  263  266  268  287  290  291  296  304  313  321  331  350
  353  358  359  360  376  377  381  382  388  395  396  399  401  403
  404  405  407  413  415  425  426  439  447  456  461  462  463  464
  471  472  485  486  509  511  512  517  518  522  524  532  541  542
  543  544  554  555  559  562  574  575  590  598  600  602  603  604
  608  610  613  615  617  623  624  626  629  634  637  641  643  644
  645  652  667  668  678  692  698  705  708  710  723  730  736  738
  743  744  750  755  764  766  769  773  778  786  787  795  803  804
  805  806  809  812  814  826  832  839  842  846  847  851  856  857
  864  866  873  885  886  889  893  896  901  904  906  910  915  916
  919  922  927  928  944  952  962  963  965  970  974  976  977  978
  981 

In [11]:
train_dataf[11]

{'mecab': '甘える こと が 嫌 だっ た が どうしても 空気 銃 が 欲しかっ た ので ねだる と 、 買 て もらえ ず 、 母 から もっとも な 意見 が 返っ て き て 困っ た から',
 'score': 2,
 'A': '1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'A_Score': 2,
 'B': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'B_Score': 0,
 'C': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'C_Score': 0,
 'D': '0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'D_Score': 1,
 'E': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'E_Score': 0,
 'Miss_Score': -1,
 'id': 1498,
 'Char': '甘 え る こ と が 嫌 だ っ た が ど う し て も 空 気 銃 が 欲 し か っ た の で ね だ る と 、 買 て も ら え ず 、 母 か ら も っ と も な 意 見 が 返 っ て き て 困 っ た か ら',
 'C_A': '1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'C_B': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [10]:
dataf_splited[0][0]

{'mecab': '甘える こと が 嫌 だっ た が どうしても 空気 銃 が 欲しかっ た ので ねだる と 、 買 て もらえ ず 、 母 から もっとも な 意見 が 返っ て き て 困っ た から',
 'score': 2,
 'A': '1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'A_Score': 2,
 'B': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'B_Score': 0,
 'C': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'C_Score': 0,
 'D': '0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'D_Score': 1,
 'E': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'E_Score': 0,
 'Miss_Score': -1,
 'id': 1498,
 'Char': '甘 え る こ と が 嫌 だ っ た が ど う し て も 空 気 銃 が 欲 し か っ た の で ね だ る と 、 買 て も ら え ず 、 母 か ら も っ と も な 意 見 が 返 っ て き て 困 っ た か ら',
 'C_A': '1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'C_B': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [12]:
dataf_splited[1][0]

{'mecab': 'たた 無 暗に 、 くしゃくしゃ する ので 自分 ながら 癪 に 障っ て 障っ て たまらなかっ た し 、 自分 の 意気地 な さ が 、 口惜しかっ た から 。',
 'score': 1,
 'A': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'A_Score': 0,
 'B': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'B_Score': 0,
 'C': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'C_Score': 0,
 'D': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'D_Score': 0,
 'E': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0',
 'E_Score': 2,
 'Miss_Score': -1,
 'id': 1085,
 'Char': 'た た 無 暗 に 、 く し ゃ く し ゃ す る の で 自 分 な が ら 癪 に 障 っ て 障 っ て た ま ら な か っ た し 、 自 分 の 意 気 地 な さ が 、 口 惜 し か っ た か ら 。',
 'C_A': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'C_B': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'C_C': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [19]:
len(dataf_splited)

5

In [15]:
train_dataf['mecab']

TypeError: ignored

In [18]:
print(train_dataf[0]['mecab'])
train_dataf[0]['mecab'].replace(' ', '')

叔父 に 待たさ れる の が 厭 に なり 普段 甘える こと は 嫌い だ が どう しよう も 無くなっ た ので 甘え て しまっ た 自分 の こと を 情けなく 思っ た


'叔父に待たされるのが厭になり普段甘えることは嫌いだがどうしようも無くなったので甘えてしまった自分のことを情けなく思った'

In [13]:
train_dataf['mecab'][0].replace(' ', '')

TypeError: ignored

In [ ]:
for qtype in ['1_5', '2_2', '2_4']:
  with open('./Y15/Y15_2-3_{}.json'.format(qtype)) as f:
    train_dataf = json.load(f)

  kf = KFold(n_splits=5, shuffle=True)
  x = np.arange(len(train_dataf))
  dataf_splited = []
  for _fold, (train_index, test_index) in enumerate(kf.split(x)):
    dataf_splited.append([train_dataf[i] for i in test_index])

  for i in range(5):
    if(i+1 > 4):
      dev_idx = 0
    else:
      dev_idx = i+1

    train_dataflist = []
    for j in range(5):
      if j != i and j != dev_idx:
        train_dataflist += dataf_splited[j]
    assert len(train_dataflist) == len(dataf_splited[0])*3

    with open('./Y15/{}_data/Y15_2-3_{}_fold{}/train_data.json'.format(qtype, qtype, i), 'w') as f:
      json.dump(train_dataflist, f, ensure_ascii=False)
    with open('./Y15/{}_data/Y15_2-3_{}_fold{}/dev_data.json'.format(qtype, qtype, i), 'w') as f:
      json.dump(dataf_splited[dev_idx], f, ensure_ascii=False)
    with open('./Y15/{}_data/Y15_2-3_{}_fold{}/test_data.json'.format(qtype, qtype, i), 'w') as f:
      json.dump(dataf_splited[i], f, ensure_ascii=False)

In [33]:
with open('./Y15/2-3_1_5_data/Y15_2-3_1_5_fold0/train_data.json') as f:
  train_dataf = json.load(f)
with open('./Y15/2-3_1_5_data/Y15_2-3_1_5_fold0/test_data.json') as f:
  test_dataf = json.load(f)
with open('./Y15/2-3_1_5_data/Y15_2-3_1_5_fold0/dev_data.json') as f:
  dev_dataf = json.load(f)

In [34]:
all_df = train_dataf + test_dataf + dev_dataf

In [35]:
def check_duplicate_dataframe(dataframes):
    seen = set()
    for df in dataframes:
        # DataFrameを文字列に変換して比較
        df_str = str(df.values)
        if df_str in seen:
            return True  # 同じDataFrameが見つかった場合
        seen.add(df_str)
    return False

In [36]:
if check_duplicate_dataframe(all_df):
  print('dup!')
else:
  print('ok')

ok


In [23]:
len(train_dataf)

1200

In [24]:
len(test_dataf)

400

In [25]:
len(dev_dataf)

400

In [ ]:
train_dataf

In [20]:
sp = [[1],[2],[3],[4],[5]]

In [21]:
for i in range(5):
  if(i+1 > 4):
    dev_idx = 0
  else:
    dev_idx = i+1

  train_dataflist = []
  for j in range(5):
    if j != i and j != dev_idx:
      train_dataflist += sp[j]
  print(train_dataflist)
  print(sp[i])
  print(sp[dev_idx])

[3, 4, 5]
[1]
[2]
[1, 4, 5]
[2]
[3]
[1, 2, 5]
[3]
[4]
[1, 2, 3]
[4]
[5]
[2, 3, 4]
[5]
[1]


In [ ]:

from sklearn.model_selection import KFold
from torch.utils.data.dataset import Subset

prompt_id = pid
data_dir = "data/fold_0"
low, high = asap_ranges[prompt_id]
train_path, dev_path, test_path = data_dir+"/train.tsv", data_dir+"/dev.tsv", data_dir+"/test.tsv"

train_dataset = get_dataset(pd.read_table(train_path, sep='\t'), prompt_id)
dev_dataset = get_dataset(pd.read_table(dev_path, sep='\t'), prompt_id)
test_dataset = get_dataset(pd.read_table(test_path, sep='\t'), prompt_id)

all_dataset = torch.utils.data.ConcatDataset([train_dataset, dev_dataset, test_dataset])
kf = KFold(n_splits=5, shuffle=True)
x = np.arange(all_dataset.__len__())
dataset_list = []
for _fold, (train_index, test_index) in enumerate(kf.split(x)):
  subset = Subset(all_dataset, test_index)
  dataset_list.append(subset)

for i in range(5):
  if(i+1 > 4):
    dev_idx = 0
  else:
    dev_idx = i+1
  train_dataset = torch.utils.data.ConcatDataset([dataset for idx, dataset in enumerate(dataset_list) if idx != i and idx != dev_idx])
  dev_dataset = dataset_list[dev_idx]
  test_dataset = dataset_list[i]
  save_data(train_dataset, 'CrossPromptDefer/TrainData_scoremodel/pt{}/fold_{}/train_dataset'.format(prompt_id, i))
  save_data(dev_dataset, 'CrossPromptDefer/TrainData_scoremodel/pt{}/fold_{}/dev_dataset'.format(prompt_id, i))
  save_data(test_dataset, 'CrossPromptDefer/TrainData_scoremodel/pt{}/fold_{}/test_dataset'.format(prompt_id, i))

In [ ]:
train_dataf[0]

{'mecab': 'スポーツ が 特定 の 企業 や 組織 によって 独占 さ れ 、 日本 の スポーツ 界 の 発展 、 スポーツ 文化 の 定着 、 スポーツ による 健全 な 社会 の 建設 も あり 得 ず 、 消え て いく 存在 に なっ て しまう 点 。',
 'score': 4,
 'A': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'A_Score': 0,
 'B': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'B_Score': 0,
 'C': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'C_Score': 0,
 'D': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'D_Score': 0,
 'E': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0',
 'E_Score': 4,
 'Miss_Score': 0,
 'id': 1660,
 'Char': 'ス ポ ー ツ が 特 定 の 企 業 や 組 織 に よ っ て 独 占 さ れ 、 日 本 の ス ポ ー ツ 界 の 発 展 、 ス ポ ー ツ 文 化 の 定 着 、 ス ポ ー ツ に よ る 健 全 な 社 会 の 建 設 も あ り 得 ず 、 消 え て い く 存 在 に な っ て し ま う 点 。',
 'C_A': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
with open('./Y14/Y14_1-2_1_3.json') as f:
  train_dataf = json.load(f)

In [ ]:
len(train_dataf)

2100

In [ ]:
with open('./Y14/Y14_2-2_2_3.json') as f:
  train_dataf = json.load(f)
train_dataf[0]

{'mecab': '「 真実 」 より も 「 幸福 」 を 優先 さ せる ため に 人々 は 後悔 や 自責 見つける と 「 真実 」 を 無視 し て 叩き つぶそ う と する こと 。',
 'score': 5,
 'A': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'A_Score': 0,
 'B': '1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'B_Score': 4,
 'C': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0',
 'C_Score': 2,
 'Miss_Score': -1,
 'id': 501,
 'Char': '「 真 実 」 よ り も 「 幸 福 」 を 優 先 さ せ る た め に 人 々 は 後 悔 や 自 責 見 つ け る と 「 真 実 」 を 無 視 し て 叩 き つ ぶ そ う と す る こ と 。',
 'C_A': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'C_B': '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0',
 'C_C': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0'}

In [ ]:
for i in train_dataf:
  if(i['score'] > 12):
    print(i)

{'mecab': '人間 の 論理 と 自然 の 論理 が 、 それぞれ せめぎ あわ ず に 自然 の 論理 が つぶさ れ 人間 の 論理 だけ で つくりださ れ た 緑 の 庭 は 、 けっして 共生 と は 言え ない から 。', 'score': 14, 'A': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0', 'A_Score': 2, 'B': '1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0', 'B_Score': 6, 'C': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0', 'C_Score': 6, 'Miss_Score': 0, 'EOS_Score': 0, 'id': 569, 'Char': '人 間 の 論 理 と 自 然 の 論 理 が 、 そ れ ぞ れ せ め ぎ あ わ ず に 自 然 の 論 理 が つ ぶ さ れ 人 間 の 論 理 だ け で つ く り だ さ れ た 緑 の 庭 は 、 け っ し て 共 生 と は 言 え な い か ら 。', 'C_A': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0', 'C_B': '1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0', 'C_C': '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1

In [ ]:
maxscore_dic = {}
for s_type in ['A_Score', 'B_Score', 'C_Score']:
  maxscore_dic[s_type]  = 0
for i in train_dataf:
  for s_type in ['A_Score', 'B_Score', 'C_Score']:
    if(maxscore_dic[s_type] < i[s_type]):
      maxscore_dic[s_type] = i[s_type]
print(maxscore_dic)

{'A_Score': 6, 'B_Score': 6, 'C_Score': 2}
